server:
  port: 9999
spring:
  activemq:
    broker-url: tcp://10.1.240.97:61616 #自己的MQ服务器地址
    user: admin
    password: admin
  jms:
    pub-sub-domain: true # false=Queue true=Topic
#定义队列名称
myTopic: boot-activemq-topic